#\u7CFB\u7EDF\u5C5E\u6027
#Sun Jan 04 02:07:31 CST 2026
java.runtime.name=Java(TM) SE Runtime Environment
sun.boot.library.path=D\:\\Java\\jdk1.8.0_131\\jre\\bin
java.vm.version=25.131-b11
java.vm.vendor=Oracle Corporation
java.vendor.url=http\://java.oracle.com/
path.separator=;
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg=sun.io
user.country=CN
user.script=
sun.java.launcher=SUN_STANDARD
sun.os.patch.level=
java.vm.specification.name=Java Virtual Machine Specification
user.dir=D\:\\code\\Study
java.runtime.version=1.8.0_131-b11
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs=D\:\\Java\\jdk1.8.0_131\\jre\\lib\\endorsed
os.arch=amd64
java.io.tmpdir=C\:\\Users\\0251217\\AppData\\Local\\Temp\\
line.separator=\r\n
java.vm.specification.vendor=Oracle Corporation
user.variant=
os.name=Windows 10
sun.jnu.encoding=GBK
java.library.path=D\:\\Java\\jdk1.8.0_131\\bin;C\:\\WINDOWS\\Sun\\Java\\bin;C\:\\WINDOWS\\system32;C\:\\WINDOWS;D\:\\Program Files (x86)\\ShadowBot;C\:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C\:\\Program Files\\IBM\\WebSphere MQ\\java\\lib;C\:\\Program Files\\IBM\\WebSphere MQ\\java\\lib64;C\:\\ProgramData\\Oracle\\Java\\javapath;C\:\\WINDOWS\\system32;C\:\\WINDOWS;C\:\\WINDOWS\\System32\\Wbem;C\:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C\:\\WINDOWS\\System32\\OpenSSH\\;C\:\\Program Files\\TortoiseSVN\\bin;D\:\\Program Files\\Git\\cmd;C\:\\Program Files\\dotnet\\;C\:\\Program Files\\Devart\\EntityDeveloper\\Console;C\:\\PROGRA~1\\IBM\\SQLLIB\\BIN;C\:\\PROGRA~1\\IBM\\SQLLIB\\FUNCTION;C\:\\Program Files\\IBM\\WebSphere MQ\\bin64;C\:\\Program Files\\IBM\\WebSphere MQ\\bin;C\:\\Program Files\\IBM\\WebSphere MQ\\tools\\c\\samples\\bin;D\:\\Program Files (x86)\\ShadowBot;C\:\\Users\\0251217\\AppData\\Local\\Microsoft\\WindowsApps;C\:\\Users\\0251217\\.dotnet\\tools;C\:\\Program Files\\Devart\\EntityDeveloper\\Console;.
java.specification.name=Java Platform API Specification
java.class.version=52.0
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=10.0
user.home=C\:\\Users\\0251217
user.timezone=Asia/Shanghai
java.awt.printerjob=sun.awt.windows.WPrinterJob
file.encoding=UTF-8
java.specification.version=1.8
java.class.path=D\:\\java\\jdk1.8.0_131\\jre\\lib\\charsets.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\deploy.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\access-bridge-64.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\cldrdata.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\dnsns.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\jaccess.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\jfxrt.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\localedata.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\nashorn.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\sunec.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\sunjce_provider.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\sunmscapi.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\sunpkcs11.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\ext\\zipfs.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\javaws.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\jce.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\jfr.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\jfxswt.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\jsse.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\management-agent.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\plugin.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\resources.jar;D\:\\java\\jdk1.8.0_131\\jre\\lib\\rt.jar;D\:\\code\\Study\\out\\production\\Study;D\:\\drivers\\mysql-connector-j-8.2.0.jar;D\:\\Program Files\\JetBrains\\IntelliJ IDEA 2025.1.3\\lib\\idea_rt.jar
user.name=0251217
java.vm.specification.version=1.8
sun.java.command=com.test.Main
java.home=D\:\\Java\\jdk1.8.0_131\\jre
sun.arch.data.model=64
user.language=zh
java.specification.vendor=Oracle Corporation
awt.toolkit=sun.awt.windows.WToolkit
java.vm.info=mixed mode
java.version=1.8.0_131
java.ext.dirs=D\:\\Java\\jdk1.8.0_131\\jre\\lib\\ext;C\:\\WINDOWS\\Sun\\Java\\lib\\ext
sun.boot.class.path=D\:\\Java\\jdk1.8.0_131\\jre\\lib\\resources.jar;D\:\\Java\\jdk1.8.0_131\\jre\\lib\\rt.jar;D\:\\Java\\jdk1.8.0_131\\jre\\lib\\sunrsasign.jar;D\:\\Java\\jdk1.8.0_131\\jre\\lib\\jsse.jar;D\:\\Java\\jdk1.8.0_131\\jre\\lib\\jce.jar;D\:\\Java\\jdk1.8.0_131\\jre\\lib\\charsets.jar;D\:\\Java\\jdk1.8.0_131\\jre\\lib\\jfr.jar;D\:\\Java\\jdk1.8.0_131\\jre\\classes
java.vendor=Oracle Corporation
file.separator=\\
java.vendor.url.bug=http\://bugreport.sun.com/bugreport/
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.endian=little
sun.desktop=windows
sun.cpu.isalist=amd64
